version: '3.8'

services:  
  mysql:
    image: mysql
    restart: always
    environment:  
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3306:3306"  
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  chatapp:
    build: ./app/
    ports:
      - 5000:5000 
    depends_on: 
      - mysql