version: '3.8'

services:
  
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:  
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3306:3306"  
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql


  # mysql:
  #   build: ./Database/
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
  #   ports:
  #     - '3306:3306'

  
  chatapp:
    build: ./ChatApp-Database/
    ports:
      - 5000:5000 
    depends_on: 
      - mysql